worker_rlimit_nofile 65535;

worker_processes auto;
events {
    worker_connections 8192;
    multi_accept on;
}

http {
    upstream backend {
        # Docker DNS will automatically resolve 'app' to all 10 replica IP addresses
        server app:3000;
        keepalive 512;
        keepalive_requests 10000;
        keepalive_timeout 65s;
    }

    server {
        listen 3000;

        location / {
            proxy_pass http://backend;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_read_timeout 60s;
            proxy_connect_timeout 10s;

            # --- MICROCACHING DISABLED FOR LOAD TESTING DYNAMIC ROUTES ---
            # proxy_cache my_cache;
            # proxy_cache_valid 200 2s; 
            # proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
            # proxy_cache_lock on;
            # proxy_cache_lock_timeout 200ms; 
        }
    }
}